### ISSUE TITLE
Google Play Service Resolver Failed in Unity 2018.1.0b5

### ISSUE THREAD

**Issue by supasonk** [googleanalytics/google-analytics-plugin-for-unity#172]
When I install the GoogleAnalyticV4 package in unity the following error code appear

`Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-analytics:LATEST

UnityEngine.Debug:LogError(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__28(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2B()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

`Gradle failed to fetch dependencies.

Failed to run 'Temp/PlayServicesResolverGradle/gradlew -b Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle --no-daemon "-PANDROID_HOME=/Users/almagest/Library/Android/sdk" "-PTARGET_DIR=/Users/almagest/Development/Unity Project/Google Analytic No Bitcode/Assets/Plugins/Android" "-PMAVEN_REPOS=https://maven.google.com" "-PPACKAGES_TO_COPY=com.google.android.gms:play-services-analytics:+"'
stdout:

stderr:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

exit code: 1

UnityEngine.Debug:LogError(Object)
GooglePlayServices.PlayServicesResolver:LogDelegate(String, LogLevel)
Google.JarResolver.PlayServicesSupport:Log(String, LogLevel, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__20(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__2B()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()`

**Comment by aykutuludag** [comment]
Same problem.

**Comment by Artemu25** [comment]
I have the simallar problem. After importing the package into emty project getting this error.

Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-base:16.0.0@aar
com.google.android.gms:play-services-basement:16.0.0@aar
com.google.android.gms:play-services-measurement-base:16.0.0@aar
com.google.android.gms:play-services-stats:16.0.0@aar
com.google.android.gms:play-services-ads-identifier:16.0.0@aar
com.google.android.gms:play-services-tasks:16.0.0@aar

Also get Warning.
Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-base:15.0.1 --> com.google.android.gms:play-services-base:16.0.0
com.google.android.gms:play-services-basement:15.0.1 --> com.google.android.gms:play-services-basement:16.0.0
com.google.android.gms:play-services-measurement-base:15.0.4 --> com.google.android.gms:play-services-measurement-base:16.0.0
com.google.android.gms:play-services-stats:15.0.1 --> com.google.android.gms:play-services-stats:16.0.0
com.google.android.gms:play-services-ads-identifier:15.0.1 --> com.google.android.gms:play-services-ads-identifier:16.0.0
com.google.android.gms:play-services-tasks:15.0.1 --> com.google.android.gms:play-services-tasks:16.0.0

**Comment by konquerprojekt** [comment]
@Artemu25 - For me work: 
top menu ASSETS > PLAY SERVICES RESOLVER > ANDROID RESOLVER > RESOLVE

**Comment by supasonk** [comment]
@Artemu25 I solve this problem by look in to others plugin. Unity won't allow multiple play-service aar. In the same project.

**Comment by s4relok** [comment]
After importing the package into empty project getting this error as well.

Tried to update SDKs, reimport, nothing helps.

Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-ads-identifier:16.0.1
com.google.android.gms:play-services-base:16.0.1
com.google.android.gms:play-services-basement:16.0.1
com.google.android.gms:play-services-measurement-base:16.0.1
com.google.android.gms:play-services-stats:16.0.1
com.google.android.gms:play-services-tasks:16.0.1


UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey4:<>m__1(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey0:<>m__0(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by c-andrews** [comment]
Hi, is there a resolution to this as I am facing the same issue?

**Comment by jnbt** [comment]
I get the same issues. Some part of the resolution doesn't seem to work when using `LASTEST` in `GoogleAnalyticsDependencies.xml`.

### My 5 cents

When using `LASTEST` the most recent version of `com.google.android.gms:play-services-analytics` is being used (at the time of writing `16.0.1`). When you look at the [Maven page](https://mvnrepository.com/artifact/com.google.android.gms/play-services-analytics/16.0.1) you will see clearly that this depends on `play-services-base` in version `15.0.1` (NOT `16.0.1`).
The resolution seems to fail in this particular case. 

### My solution

By hardcoding version `12.0.1` via `Assets/GoogleAnalytic/GoogleAnalyticsDependencies.xml` the issue is solved:

```xml
<dependencies>
  <!-- Android dependencies are specified under the "androidPackages" element.
       Each "androidPackage" element contains the attributes of an Android
       dependency (e.g AAR, JAR reference). -->
  <androidPackages>
    <!-- The "spec" attribute is *required* and provides the Maven package
         specification.

         Currently this only supports group:artifact:version_specification where
         group:artifact:version_specification references a Maven package that
         can be located in:
         * Maven central.
         * Google's Maven repo.
         * Local Android SDK Maven repo.

         Additional repositories can be added using the "repositories" element.
    -->
    <androidPackage spec="com.google.android.gms:play-services-analytics:12.0.1">
      <!-- androidSdkPackageIds is optional and contains the set of Android
           SDK package manager components (packages) this package requires.

           If the package can't be found in any of the specified repositories,
           the dependency resolver will attempt to install the set of Android
           SDK packages specified here and then attempt resolution again.
      -->
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
      <!-- "repositories" are optional and contain the set of additional
           repository URIs to search for this package. -->
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```

**Comment by jeeteshb** [comment]
@jnbt 
Hi I have done the <androidPackage spec="com.google.android.gms:play-services-analytics:12.0.1">

But still getting the below error for Android Project.  Any help on the same will be really appreciated.

Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-analytics-impl-license:15.0.1
com.google.android.gms:play-services-analytics-impl:15.0.1
com.google.android.gms:play-services-analytics-license:15.0.1
com.google.android.gms:play-services-analytics:15.0.1
com.google.android.gms:play-services-tagmanager-v4-impl-license:15.0.1
com.google.android.gms:play-services-tagmanager-v4-impl:15.0.1

**Comment by jnbt** [comment]
@jeeteshb I can only assume that your project has some Android dependency loading `15.0.1`. Which plugins are you using?

**Comment by jeeteshb** [comment]
I was using googleSignIn plugin, google analytics plugin, voxel buster,
stans assets, vuforia plugins.

So any of these plugins have the dependencies for 15.0.1 in your opinion.

Thanks,
Jeetesh
